"""create_seeds_table

Revision ID: 2f1d1ce031e3
Revises: cf84206edb65
Create Date: 2025-03-15 23:51:09.954317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f1d1ce031e3'
down_revision: Union[str, None] = 'cf84206edb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('germination_rate', sa.Float(), nullable=True),
    sa.Column('germ_date', sa.Date(), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.Column('growth', sa.String(length=100), nullable=True),
    sa.Column('seed_depth', sa.Float(), nullable=True),
    sa.Column('spacing', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seeds_id'), 'seeds', ['id'], unique=False)
    op.drop_index('ix_seed_packets_id', table_name='seed_packets')
    op.drop_table('seed_packets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_packets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('variety', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('germination_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('germ_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('maturity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('growth', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('seed_depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('spacing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seed_packets_pkey')
    )
    op.create_index('ix_seed_packets_id', 'seed_packets', ['id'], unique=False)
    op.drop_index(op.f('ix_seeds_id'), table_name='seeds')
    op.drop_table('seeds')
    # ### end Alembic commands ###
