"""update_seed_image_relationships

Revision ID: 4a7c3d06e129
Revises: 4fd57b9690a6
Create Date: 2025-03-18 00:19:20.155017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7c3d06e129'
down_revision: Union[str, None] = '4fd57b9690a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
