"""add_structured_data_to_images

Revision ID: 7919127e2fa8
Revises: 4a7c3d06e129
Create Date: 2025-03-18 00:41:07.598400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7919127e2fa8'
down_revision: Union[str, None] = '4a7c3d06e129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('structured_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'structured_data')
    # ### end Alembic commands ###
