"""remove germination_rate, germ_date, and maturity from seeds table

Revision ID: 96245d022f36
Revises: 20250415_remove_growth_from_seed
Create Date: 2025-04-15 18:17:49.002493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96245d022f36'
down_revision: Union[str, None] = '20250415_remove_growth_from_seed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'germ_date')
    op.drop_column('seeds', 'germination_rate')
    op.drop_column('seeds', 'maturity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('maturity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('germination_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('germ_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
