"""remove_quantity_field

Revision ID: 998185dcef1b
Revises: 7f1ee3867cc8
Create Date: 2025-03-24 19:31:47.517020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998185dcef1b'
down_revision: Union[str, None] = '7f1ee3867cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
