"""drop expected_germination_time and expected_maturity_time from plantings

Revision ID: a087a8f7a47d
Revises: c1dd2ce036a5
Create Date: 2025-04-20 23:35:27.545053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a087a8f7a47d'
down_revision: Union[str, None] = 'c1dd2ce036a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plantings', 'expected_maturity_time')
    op.drop_column('plantings', 'expected_germination_time')
    op.add_column('seeds', sa.Column('germination_rate', sa.Float(), nullable=True))
    op.add_column('seeds', sa.Column('maturity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'maturity')
    op.drop_column('seeds', 'germination_rate')
    op.add_column('plantings', sa.Column('expected_germination_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plantings', sa.Column('expected_maturity_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
