"""drop ocr_text field from images

Revision ID: c1dd2ce036a5
Revises: 96245d022f36
Create Date: 2025-04-17 17:52:49.425805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1dd2ce036a5'
down_revision: Union[str, None] = '96245d022f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'ocr_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
