"""create_seed_packet_table_with_timestamps

Revision ID: cf84206edb65
Revises: 
Create Date: 2025-03-15 17:11:12.800367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf84206edb65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('germination_rate', sa.Float(), nullable=True),
    sa.Column('germ_date', sa.Date(), nullable=True),
    sa.Column('maturity', sa.Integer(), nullable=True),
    sa.Column('growth', sa.String(length=100), nullable=True),
    sa.Column('seed_depth', sa.Float(), nullable=True),
    sa.Column('spacing', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_packets_id'), 'seed_packets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_packets_id'), table_name='seed_packets')
    op.drop_table('seed_packets')
    # ### end Alembic commands ###
