"""drop purchase_date, expiration_date, germination_rate, maturity from seeds

Revision ID: f990212e2a3c
Revises: a087a8f7a47d
Create Date: 2025-04-21 00:14:54.023418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f990212e2a3c'
down_revision: Union[str, None] = 'a087a8f7a47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'purchase_date')
    op.drop_column('seeds', 'germination_rate')
    op.drop_column('seeds', 'maturity')
    op.drop_column('seeds', 'expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('maturity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('germination_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('seeds', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
