name: plant-tracker

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # Mount app directory
      - ./uploads:/app/uploads  # Mount uploads directory
      - ./utils:/app/utils  # Mount utils directory for Gemini vision API
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-7-sonnet-20250219}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-pro-exp-03-25}
      - VISION_API_PROVIDER=${VISION_API_PROVIDER:-gemini}  # Use .env setting with fallback to gemini
      # - BULK_IMPORT_API_KEY=your_secret_key_here # Uncomment and set a secure key
      # Add other environment variables as needed
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5433}:5432"  # Changed to use 5433 as default external port
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:  # Persistent volume for database data